[package]
name = "simple-lambda-local-docker-build"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_runtime = "0.13.0"
serde = "1.0.215"
serde_json = "1.0.133"
tokio = { version = "1", features = ["macros"] }
